# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.2/filebeat-module-elasticsearch.html

- module: elasticsearch
  # Server log
  server:
    enabled: true
    var.paths: [ "/var/log/elasticsearch/elasticsearch_server.log" ]
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

    # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
    #var.convert_timezone: false

  gc:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:
    var.paths: [ "/var/log/elasticsearch/gc.log.0.current" ]

  audit:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:
    var.paths: [ "/var/log/elasticsearch/elasticsearch_audit.json" ]

    # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
    #var.convert_timezone: false

  slowlog:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:
    var.paths: [ "/var/log/elasticsearch/elasticsearch_index_indexing_slowlog.json","/var/log/elasticsearch/elasticsearch_index_indexing_slowlog.log","/var/log/elasticsearch/elasticsearch_index_search_slowlog.json","/var/log/elasticsearch/elasticsearch_index_search_slowlog.log" ]

    # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
    #var.convert_timezone: false

  deprecation:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: [ "/var/log/elasticsearch/elasticsearch_deprecation.json","/var/log/elasticsearch/elasticsearch_deprecation.log" ]

    # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
    #var.convert_timezone: false

