# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.2/filebeat-module-kibana.html

- module: kibana
  # All logs
  log:
    enabled: true
    var.paths: [ "/var/log/kibana.log" ]
